# Generated by Django 5.2.1 on 2025-05-20 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anggaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun', models.IntegerField()),
                ('sektor', models.CharField(max_length=100)),
                ('alokasi', models.DecimalField(decimal_places=2, max_digits=15)),
                ('deskripsi', models.TextField(blank=True)),
            ],
        ),
    ]
