# Generated by Django 5.2.1 on 2025-06-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apbd', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.URLField(blank=True),
        ),
    ]
